return {
	"stevearc/dressing.nvim",
	event = "VeryLazy",
	opts = {
		input = {
			enabled = true,
			default_prompt = "Input:",
			trim_prompt = true,
			title_pos = "center",
			insert_only = true,
			start_in_insert = true,
			border = "rounded",
			relative = "cursor",
			prefer_width = 40,
			width = nil,
			max_width = { 140, 0.9 },
			min_width = { 20, 0.2 },
			buf_options = {},
			win_options = {
				wrap = false,
				list = true,
				listchars = "precedes:…,extends:…",
				sidescrolloff = 0,
				winhighlight = "NormalFloat:Normal,FloatBorder:DiagnosticInfo",
			},
			mappings = {
				n = {
					["<Esc>"] = "Close",
					["<CR>"] = "Confirm",
				},
				i = {
					["<C-c>"] = "Close",
					["<CR>"] = "Confirm",
					["<Up>"] = "HistoryPrev",
					["<Down>"] = "HistoryNext",
				},
			},
		},
		select = {
			enabled = true,
			backend = { "telescope", "builtin", "nui" },
			trim_prompt = true,
			telescope = nil, -- Use default telescope theme
			builtin = {
				show_numbers = true,
				border = "rounded",
				relative = "editor",
				buf_options = {},
				win_options = {
					cursorline = true,
					cursorlineopt = "both",
					winhighlight = "NormalFloat:Normal,FloatBorder:DiagnosticInfo",
				},
				width = nil,
				max_width = { 140, 0.8 },
				min_width = { 40, 0.2 },
				height = nil,
				max_height = 0.9,
				min_height = { 10, 0.2 },
				mappings = {
					["<Esc>"] = "Close",
					["<C-c>"] = "Close",
					["<CR>"] = "Confirm",
				},
			},
			format_item_override = {},
			get_config = nil,
		},
	},
}
