return {
	"folke/which-key.nvim",
	event = "VimEnter",
	opts = {
		preset = "helix",
		icons = {
			mappings = vim.g.have_nerd_font,
			keys = vim.g.have_nerd_font and {} or {
				Up = "<Up> ",
				Down = "<Down> ",
				Left = "<Left> ",
				Right = "<Right> ",
				C = "<C-…> ",
				M = "<M-…> ",
				D = "<D-…> ",
				S = "<S-…> ",
				CR = "<CR> ",
				Esc = "<Esc> ",
				ScrollWheelDown = "<ScrollWheelDown> ",
				ScrollWheelUp = "<ScrollWheelUp> ",
				NL = "<NL> ",
				BS = "<BS> ",
				Space = "<Space> ",
				Tab = "<Tab> ",
				F1 = "<F1>",
				F2 = "<F2>",
				F3 = "<F3>",
				F4 = "<F4>",
				F5 = "<F5>",
				F6 = "<F6>",
				F7 = "<F7>",
				F8 = "<F8>",
				F9 = "<F9>",
				F10 = "<F10>",
				F11 = "<F11>",
				F12 = "<F12>",
			},
		},
		spec = {
			{ "<leader>b", group = "Buffers", icon = "" },
			{ "<leader>d", group = "Debug", icon = "" },
			{ "<leader>e", group = "File explorer", icon = "" },
			{ "<leader>f", group = "Find", icon = "" },
			{ "<leader>g", group = "Git", icon = "" },
			{ "<leader>gC", group = "Git Checkout", icon = "" },
			{ "<leader>h", group = "Hunk", icon = "" },
			{ "<leader>s", group = "Search", icon = "" },
			{ "<leader>t", group = "Toggle", icon = "" },
			{ "<leader>r", group = "Rename", icon = "" },
		},
	},
}
